// Package sbom reads Flatcar's SPDX SBOM files and extracts the packages
// they describe, split into two groups matched against different
// vulnerability sources:
//
//   - ebuild (Portage) packages, matched against the GLSA corpus
//     (internal/glsa, internal/match).
//   - golang/cargo packages, matched against OSV.dev (internal/osv).
//
// Flatcar publishes one SBOM per released image
// (flatcar_production_image_sbom.json), in SPDX 2.3 JSON format, generated by
// Syft. Each package appears as an SPDX package whose external references
// include a "purl" identifying its ecosystem, e.g.
// "pkg:ebuild/<category>/<name>@<version>" or "pkg:golang/<module>@<version>".
// Other purl types (e.g. statically linked binaries with no purl at all) are
// ignored here for now.
package sbom

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Package is a single package extracted from an SBOM, either an ebuild
// (Portage) package or a golang/cargo module (see Document.OSVPackages).
type Package struct {
	// Category is the Portage category (e.g. "sys-apps") for ebuild
	// packages, or the OSV.dev ecosystem purl type (e.g. "golang",
	// "cargo") for OSVPackages entries.
	Category string
	// Name is the package name within its category (ebuild), or the
	// module/crate path (golang/cargo), e.g. "systemd" or
	// "cloud.google.com/go/storage".
	Name string
	// Version is the installed package version, e.g. "255.4-r2" or
	// "v1.57.0".
	Version string
	// PURL is the original package URL as it appeared in the SBOM, e.g.
	// "pkg:ebuild/sys-apps/systemd@255.4-r2". Kept verbatim (including
	// any subpath/qualifiers) so it can be reused as-is in VEX output.
	PURL string
}

// CategoryName returns the "category/name" identifier used to match against
// GLSA <package name="..."> entries, or as a general sort/display key for
// non-ebuild packages.
func (p Package) CategoryName() string {
	return p.Category + "/" + p.Name
}

// document mirrors only the subset of the SPDX 2.3 JSON schema this package
// needs. Fields not used for VEX generation are intentionally omitted.
type document struct {
	Name     string        `json:"name"`
	Packages []spdxPackage `json:"packages"`
}

type spdxPackage struct {
	Name         string        `json:"name"`
	VersionInfo  string        `json:"versionInfo"`
	ExternalRefs []externalRef `json:"externalRefs"`
}

type externalRef struct {
	ReferenceCategory string `json:"referenceCategory"`
	ReferenceType     string `json:"referenceType"`
	ReferenceLocator  string `json:"referenceLocator"`
}

// ebuildPurlPrefix is the purl type Syft assigns to Portage-managed packages.
const ebuildPurlPrefix = "pkg:ebuild/"

// osvEcosystemPurlPrefixes maps a purl "type" prefix to the ecosystem tag
// stored in Package.Category for packages OSV.dev can be queried about.
// Cargo has no real-world coverage in Flatcar's SBOM today (verified: 0
// "cargo" purls in the current production SBOM, only "golang" and
// "ebuild"), but is included since OSV.dev supports it identically and
// Flatcar may pull in Rust components later.
var osvEcosystemPurlPrefixes = map[string]string{
	"pkg:golang/": "golang",
	"pkg:cargo/":  "cargo",
}

// Document holds the SBOM-level metadata plus every package it describes,
// split by which vulnerability source can match against it.
type Document struct {
	// Name is the SPDX document's "name" field. For Flatcar SBOMs this is a
	// build path that embeds the channel and release version, e.g.
	// ".../amd64-usr/stable-4593.2.4-a1/rootfs-with-sysext-pkgs".
	Name string
	// Packages are the ebuild (Portage) packages, matched against GLSA.
	Packages []Package
	// OSVPackages are the golang/cargo packages, matched against OSV.dev
	// (internal/osv). These have zero GLSA coverage today (~1070 of
	// ~1400 packages in the current production SBOM).
	OSVPackages []Package
}

// Load reads an SPDX JSON SBOM from path and returns every package it
// describes, split into Packages (ebuild) and OSVPackages (golang/cargo),
// along with the document's own metadata.
func Load(path string) (Document, error) {
	raw, err := os.ReadFile(path) //nolint:gosec // path is an explicit user-provided CLI flag.
	if err != nil {
		return Document{}, fmt.Errorf("reading SBOM file %q: %w", path, err)
	}

	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return Document{}, fmt.Errorf("parsing SBOM file %q as SPDX JSON: %w", path, err)
	}

	result := Document{Name: doc.Name}
	for _, sp := range doc.Packages {
		if purl, ok := ebuildPurl(sp); ok {
			if category, name, ok := parseEbuildPurl(purl); ok {
				result.Packages = append(result.Packages, Package{
					Category: category,
					Name:     name,
					Version:  sp.VersionInfo,
					PURL:     purl,
				})
			}
			continue
		}

		if purl, ecosystem, ok := osvPurl(sp); ok {
			if name, ok := parseOSVPurl(purl, ecosystem); ok && isQueryableVersion(sp.VersionInfo) {
				result.OSVPackages = append(result.OSVPackages, Package{
					Category: ecosystem,
					Name:     name,
					Version:  sp.VersionInfo,
					PURL:     purl,
				})
			}
		}
	}

	return result, nil
}

// ebuildPurl returns the ebuild purl of an SPDX package, if it has one.
func ebuildPurl(sp spdxPackage) (string, bool) {
	for _, ref := range sp.ExternalRefs {
		if ref.ReferenceType == "purl" && strings.HasPrefix(ref.ReferenceLocator, ebuildPurlPrefix) {
			return ref.ReferenceLocator, true
		}
	}
	return "", false
}

// osvPurl returns the golang/cargo purl of an SPDX package and its
// ecosystem tag, if it has one.
func osvPurl(sp spdxPackage) (purl, ecosystem string, ok bool) {
	for _, ref := range sp.ExternalRefs {
		if ref.ReferenceType != "purl" {
			continue
		}
		for prefix, eco := range osvEcosystemPurlPrefixes {
			if strings.HasPrefix(ref.ReferenceLocator, prefix) {
				return ref.ReferenceLocator, eco, true
			}
		}
	}
	return "", "", false
}

// parseEbuildPurl extracts category and name from a purl of the form
// "pkg:ebuild/<category>/<name>@<version>". The version is intentionally
// read from the SPDX package's own versionInfo field instead (it is
// unescaped there, whereas the purl version component may be percent-encoded).
func parseEbuildPurl(purl string) (category, name string, ok bool) {
	rest := strings.TrimPrefix(purl, ebuildPurlPrefix)
	rest, _, _ = strings.Cut(rest, "@") // drop "@version" and any "?qualifiers"
	rest, _, _ = strings.Cut(rest, "?")

	category, name, found := strings.Cut(rest, "/")
	if !found || category == "" || name == "" {
		return "", "", false
	}
	return category, name, true
}

// parseOSVPurl extracts the module/crate path from a purl of the form
// "pkg:<ecosystem>/<name>@<version>[?qualifiers][#subpath]". As with
// parseEbuildPurl, the version itself is read from versionInfo, not here.
//
// Some Syft-generated golang purls describe build-internal packages rather
// than real, queryable modules, e.g. "pkg:golang/../api@(devel)" for a
// package built from a relative path within its own main module (verified
// against Flatcar's current production SBOM: 24 such "(devel)" entries, all
// also using a relative "../" name). Both are rejected here: a name isn't
// usable if it's empty or starts with "." (relative path component), and
// isQueryableVersion separately rejects "(devel)"-style placeholder
// versions.
func parseOSVPurl(purl, ecosystem string) (name string, ok bool) {
	rest := strings.TrimPrefix(purl, "pkg:"+ecosystem+"/")
	name, _, found := strings.Cut(rest, "@")
	if !found || name == "" || strings.HasPrefix(name, ".") {
		return "", false
	}
	return name, true
}

// isQueryableVersion reports whether v looks like a real version OSV.dev
// could be queried about, rejecting empty strings and Go's "(devel)"-style
// pseudo-versions (which have no meaningful version to query).
func isQueryableVersion(v string) bool {
	v = strings.TrimSpace(v)
	return v != "" && !strings.HasPrefix(v, "(")
}
