// Package sbom reads Flatcar's SPDX SBOM files and extracts the ebuild
// (Portage) packages they describe.
//
// Flatcar publishes one SBOM per released image
// (flatcar_production_image_sbom.json), in SPDX 2.3 JSON format, generated by
// Syft. Each Portage package appears as an SPDX package whose external
// references include a "purl" of the form "pkg:ebuild/<category>/<name>@<version>".
// Non-ebuild packages (e.g. Go modules, statically linked binaries) use other
// purl types and are ignored here for now (see docs/plan.md, Future Phase
// candidate #1: OSV.dev integration).
package sbom

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// Package is a single ebuild (Portage) package extracted from an SBOM.
type Package struct {
	// Category is the Portage category, e.g. "sys-apps".
	Category string
	// Name is the package name within its category, e.g. "systemd".
	Name string
	// Version is the installed package version, e.g. "255.4-r2".
	Version string
	// PURL is the original package URL as it appeared in the SBOM, e.g.
	// "pkg:ebuild/sys-apps/systemd@255.4-r2".
	PURL string
}

// CategoryName returns the "category/name" identifier used to match against
// GLSA <package name="..."> entries.
func (p Package) CategoryName() string {
	return p.Category + "/" + p.Name
}

// document mirrors only the subset of the SPDX 2.3 JSON schema this package
// needs. Fields not used for VEX generation are intentionally omitted.
type document struct {
	Name     string        `json:"name"`
	Packages []spdxPackage `json:"packages"`
}

type spdxPackage struct {
	Name         string        `json:"name"`
	VersionInfo  string        `json:"versionInfo"`
	ExternalRefs []externalRef `json:"externalRefs"`
}

type externalRef struct {
	ReferenceCategory string `json:"referenceCategory"`
	ReferenceType     string `json:"referenceType"`
	ReferenceLocator  string `json:"referenceLocator"`
}

// ebuildPurlPrefix is the purl type Syft assigns to Portage-managed packages.
const ebuildPurlPrefix = "pkg:ebuild/"

// Document holds the SBOM-level metadata plus every ebuild package it
// describes.
type Document struct {
	// Name is the SPDX document's "name" field. For Flatcar SBOMs this is a
	// build path that embeds the channel and release version, e.g.
	// ".../amd64-usr/stable-4593.2.4-a1/rootfs-with-sysext-pkgs".
	Name     string
	Packages []Package
}

// LoadEbuildPackages reads an SPDX JSON SBOM from path and returns every
// ebuild package it describes, along with the document's own metadata.
func LoadEbuildPackages(path string) (Document, error) {
	raw, err := os.ReadFile(path) //nolint:gosec // path is an explicit user-provided CLI flag.
	if err != nil {
		return Document{}, fmt.Errorf("reading SBOM file %q: %w", path, err)
	}

	var doc document
	if err := json.Unmarshal(raw, &doc); err != nil {
		return Document{}, fmt.Errorf("parsing SBOM file %q as SPDX JSON: %w", path, err)
	}

	var pkgs []Package
	for _, sp := range doc.Packages {
		purl, ok := ebuildPurl(sp)
		if !ok {
			continue
		}

		category, name, ok := parseEbuildPurl(purl)
		if !ok {
			continue
		}

		pkgs = append(pkgs, Package{
			Category: category,
			Name:     name,
			Version:  sp.VersionInfo,
			PURL:     purl,
		})
	}

	return Document{Name: doc.Name, Packages: pkgs}, nil
}

// ebuildPurl returns the ebuild purl of an SPDX package, if it has one.
func ebuildPurl(sp spdxPackage) (string, bool) {
	for _, ref := range sp.ExternalRefs {
		if ref.ReferenceType == "purl" && strings.HasPrefix(ref.ReferenceLocator, ebuildPurlPrefix) {
			return ref.ReferenceLocator, true
		}
	}
	return "", false
}

// parseEbuildPurl extracts category and name from a purl of the form
// "pkg:ebuild/<category>/<name>@<version>". The version is intentionally
// read from the SPDX package's own versionInfo field instead (it is
// unescaped there, whereas the purl version component may be percent-encoded).
func parseEbuildPurl(purl string) (category, name string, ok bool) {
	rest := strings.TrimPrefix(purl, ebuildPurlPrefix)
	rest, _, _ = strings.Cut(rest, "@") // drop "@version" and any "?qualifiers"
	rest, _, _ = strings.Cut(rest, "?")

	category, name, found := strings.Cut(rest, "/")
	if !found || category == "" || name == "" {
		return "", "", false
	}
	return category, name, true
}
